build:
  version: 2.0
accounts:
  message: "Welcome to Easy Bank Account Section--- QA Section"
  contactDetails:
    name: "Chatur Rama Lingam"
    email: "chaturramalingam@gmail.com"
  onCallSupport:
    - (940) 435-8688
    - (469) 345-9084
spring:
  config:
    activate:
      on-profile: "qa"
