accounts:
  message: "Welcome to Easy Bank Account Section--- PROD Section"
  contactDetails:
    name: "Hello Nischal I think now this works fine! what the hell!!!!"
    email: "{cipher}bbd839af1b7161645e12dd8de99fd5d637e2403347b4e87252eedcafd216af9335b494e66a8408e449e69e0ee82d7fe6"
  onCallSupport:
    - (940) 435-8688
    - (469) 345-9084
build:
  version: 1.0
spring:
  config:
    activate:
      on-profile: "prod"
