cards:
  message: "Welcome to Easy Bank Card --Prod Section"
  contactDetails:
    name: "Paras Sharma, k cha halkhabar"
    email: "paras@gmail.com"
  onCallSupport:
    - (940) 435-8688
    - (469) 345-764567
build:
  version: 1.0
spring:
  config:
    activate:
      on-profile: "prod"
