loans:
  message: "Welcome to Easy Bank Loan Section--- PROD Section"
  contactDetails:
    name: "Anita Shah Thikai cha "
    email: "anita@gmail.com"
  onCallSupport:
    - (940) 435-8688
    - (469) 345-6666
build:
  version: 1.0
spring:
  config:
    activate:
      on-profile: "prod"
