build:
  version: 2.0
accounts:
  message: "Welcome to Easy Bank loans Section--- QA Section"
  contactDetails:
    name: "hari Timisna"
    email: "hari@gmail.com"
  onCallSupport:
    - (940) 435-8688
    - (469) 345-9084
spring:
  config:
    activate:
      on-profile: "qa"
