loans:
  message: "Welcome to Easy Bank Loan Section--- PROD Section"
  contactDetails:
    name: "Anita Shah"
    email: "anita@gmail.com"
  onCallSupport:
    - (940) 435-8688
    - (469) 345-9084
build:
  version: 1.0
spring:
  config:
    activate:
      on-profile: "prod"
